version: "3.9"
services:
  prometheus:
    image: prom/prometheus
    user: root #bypasses security issues when trying to create files/folders
    ports:
      - "9090:9090"
    volumes:
      - "./container-data/prometheus:/prometheus"
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/"
      - "./grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/"
      - "./grafana/dashboards/:/var/lib/grafana/dashboards/"
      - "./grafana/defaults.ini:/usr/share/grafana/conf/defaults.ini"
  net_test:
    # image: ghcr.io/slpixe/net-test:master useful for running on end server 
    build: . # useful if have the full code on the end-device
    ports:
      - "2112:2112"
  # debug:
  #   image: alpine
